name: terraform-plan

on:
  pull_request:
    branches: [dev, stage, prod]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: $GITHUB_BASE_REF
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA}}
    defaults:
      run:
        working-directory: Infrastructure/terraform/gcp/iac
    steps:
      - uses: ./.github/terraform.yaml
        with:
          tf-cloud-token: ${{secrets.TERRAFORM_API_TOKEN}}
          tfvar-name: "${GITHUB_BASE_REF}.tfvars"

      # generate plain output
      # - run: terraform show -no-color terraform.plan > terraform.text

      # - run : gh pr comment ${{ github.event.number }} --body-file terraform.text
