name: terraform-plan

on:
  pull_request:
    branches: [main]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - run: terraform init
      - run: terraform plan -out terraform.plan

      # generate plain output
      - run: terraform show -no-color terraform.plan > terraform.text

      - run : gh pr comment ${{ github.event.number }} --body-file terraform.text
